LPS-112056 Move ResourceActionsBag to portal-kernel
dantewang/liferay-portal pull request #1785
Opened 2020-10-26 07:33 UTC by yuhai

@dantewang, the pr is based on https://github.com/dantewang/liferay-portal/pull/1783. It includes LPS-117531 and LPS-121111.

2020-10-26 07:33 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-10-26 07:33 UTC, yuhai commented
ci:test:sf

2020-10-26 07:33 UTC, yuhai commented
ci:test:relevant

2020-10-26 07:33 UTC, yuhai commented
ci:test

2020-10-26 07:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-24.liferay.com/job/test-portal-source-format/363/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-24.liferay.com//userContent/jobs/test-portal-source-format/builds/363/jenkins-report.html">here</a>.</b></p>

2020-10-26 07:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/37b0a7b5db3986072d5359a90769fb94d1956526">37b0a7b5db3986072d5359a90769fb94d1956526</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/yuhai/liferay-portal/tree/LPS-112056">LPS-112056</a><br/>Branch GIT ID: <a href="https://github.com/yuhai/liferay-portal/commit/4314d6033742d687a41801d17222e3dd9c4a5365">4314d6033742d687a41801d17222e3dd9c4a5365</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-24.liferay.com/job/test-portal-source-format/363/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-24.liferay.com/userContent/jobs/test-portal-source-format/builds/363/jenkins-report.html">here</a>.</h5></details></html>

2020-10-26 07:40 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-24.liferay.com/job/test-portal-source-format/363/">test-portal-source-format#363</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-24.liferay.com/userContent/jobs/test-portal-source-format/builds/363/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/dantewang/liferay-portal/pull/1785">dantewang#1785</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/53829.aspx">master - yuhai > dantewang - PR#1785 - 2020-10-26[00:35:13]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/11889/">publish-spira-report#11889</a><br />

2020-10-26 07:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/3751/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3751/jenkins-report.html">here</a>.</b></p>

2020-10-26 07:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/7392/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-16.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7392/jenkins-report.html">here</a>.</b></p>

2020-10-26 10:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 14 out of 14 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 216 out of 220 jobs passed in 2 hours 43 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/37b0a7b5db3986072d5359a90769fb94d1956526">37b0a7b5db3986072d5359a90769fb94d1956526</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/424ab1158c689b11bc409031cffca77c71b5b194">424ab1158c689b11bc409031cffca77c71b5b194</a></p><details><summary><strong>ci:test:stable - 14 out of 14 jobs PASSED</strong></summary><details><summary><strong>14 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/339712/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475941/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/366553/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/1</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/313354/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/2</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456156/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/3</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/452393/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/4</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/415582/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/5</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/308781/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475935/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414833/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/339707/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/366542/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/425155/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/308784/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 215 out of 220 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/3751/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444475/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/95</strong></strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/442458/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414834/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</strong></strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/205718/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</strong></strike></a></li></ul></div><details><summary><strong>215 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/339710/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/339714/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/339712/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/313348/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444474/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444483/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/10</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/394530/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/100</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/475947/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/101</a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/415587/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/102</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/308785/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/103</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/205717/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/104</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/368692/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/105</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/425157/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/106</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/452397/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/107</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/366559/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90- [...]

2020-10-26 12:23 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:default - 340 out of 353 jobs passed in 4 hours 25 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/37b0a7b5db3986072d5359a90769fb94d1956526">37b0a7b5db3986072d5359a90769fb94d1956526</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/424ab1158c689b11bc409031cffca77c71b5b194">424ab1158c689b11bc409031cffca77c71b5b194</a></p><details><summary><strong>ci:test:default - 340 out of 353 jobs PASSED</strong></summary><div><h4>13 Failed Jobs:</h4><ul><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest(master)/7392/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/394538/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/archived-modules-test-jdk8</strong></strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/394539/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/199</strong></strike></a></li><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/415613/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/219</strong></strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/414858/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/49</strong></strike></a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/308806/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/6</strong></strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/452425/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-hot-deployment-jdk8</strong></strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/205729/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8</strong></strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/339732/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8</strong></strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/425182/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8</strong></strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/394545/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/source-format-jdk8</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/466747/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/tck-jdk8</strong></strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/453345/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/unit-jdk8</strong></strike></a></li></ul></div><details><summary><strong>340 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/442459/">test-portal-acceptance-pullrequest-batch(master)/archived-module-smoke-jdk8</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/453337/">test-portal-acceptance-pullrequest-batch(master)/bundle-blacklist-restart-jdk8</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/394536/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8</a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/406152/">test-portal-acceptance-pullrequest-batch(master)/compile-jsp-jdk8</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/308802/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/447897/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-jboss72-mysql57-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/452411/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-db2111-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444502/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mariadb102-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/425175/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/466754/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/368703/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql80-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444646/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-oracle122-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444650/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-postgresql10-jdk8/0</a></li><li><a href="https://test-1-20.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/427303/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-postgresql121-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/366568/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-sqlserver2017-jdk8/0</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/318704/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-sqlserver2019-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444499/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-sybase160-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/444655/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-weblogic122-mysql57-jdk8/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456170/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-websphere90-mysql57-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/366583/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly140-mariadb102-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/339730/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly170-mariadb [...]

2020-10-29 06:32 UTC, dantewang requested changes

2020-10-29 06:32 UTC, dantewang commented on portal-kernel/src/com/liferay/portal/kernel/security/permission/ResourceActionsBagPool.java
> +		synchronized (_resourceActionsBagPool) {
@yuhai What about using `ConcurrentHashMap.compute*` methods here? They are implemented to be atomic.

For example:

```
		return _resourceActionsBagPool.compute(
			name,
			(key, value) -> {
				if (force || (value == null)) {
					return resourceActionsBag;
				}

				return value;
			});
```

2020-10-29 06:32 UTC, dantewang commented on portal-kernel/src/com/liferay/portal/kernel/security/permission/ResourceActionsBagPool.java
> +public class ResourceActionsBagPool {
@yuhai Did you add this class following other "bag" classes (like `PortletBagPool`)? `PortletBagPool` is used because `PortletBagFactory` does not register the bag as service.

However our final goal is to register `ResourceActionsBag` instances as OSGi services. Then from the bags' users' aspect, they just need to track one or more bags using service tracker or service tracker map. This is why in my original pull I replaced `ResourceActions` APIs that return specific actions lists with APIs that return the whole bag.

And you want to make `ResourceActionsBag` immutable in LPS-121111 commits. But the finally extracted  `ResourceActionsBagImpl` still directly returns its `Set<String>`s, which is not immutable. **Immutable means a class does not provide any public API to change its content.**

2020-10-29 06:32 UTC, closed without merging

2020-10-29 06:33 UTC, dantewang commented
@yuhai Please see my comments and reconsider the changes. Thanks

2020-10-29 07:19 UTC, yuhai commented
@dantewang, got it.