Lps 124576
dantewang/liferay-portal pull request #1833
Opened 2020-12-09 09:07 UTC by slnn

Hi @dantewang 

This pull aims to update ddl sample data generation according to the head of master.

/cc @tinatian

Lily

2020-12-09 09:07 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-12-09 09:08 UTC, slnn commented
ci:test:relevant

2020-12-09 09:08 UTC, slnn commented
ci:test:sf

2020-12-09 09:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/4699/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-source-format/builds/4699/jenkins-report.html">here</a>.</b></p>

2020-12-09 09:13 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/af6e0123bc66b7202e413a5943d275dc638f0f7f">af6e0123bc66b7202e413a5943d275dc638f0f7f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/slnn/liferay-portal/tree/LPS-124576">LPS-124576</a><br/>Branch GIT ID: <a href="https://github.com/slnn/liferay-portal/commit/dfecf1f2c9ea5737eb3c55614beabc13243de24b">dfecf1f2c9ea5737eb3c55614beabc13243de24b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/4699/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/4699/jenkins-report.html">here</a>.</h5></details></html>

2020-12-09 09:14 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-6.liferay.com/job/test-portal-source-format/4699/">test-portal-source-format#4699</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/4699/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/dantewang/liferay-portal/pull/1833">dantewang#1833</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/69581.aspx">master - slnn > dantewang - PR#1833 - 2020-12-09[01:10:01]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/15932/">publish-spira-report#15932</a><br />

2020-12-09 10:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest(master)/7601/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7601/jenkins-report.html">here</a>.</b></p>

2020-12-09 13:04 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 21 out of 21 jobs passed in 2 hours 58 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ff774b85e421de0b8d1338adf7f2e2454c734303">ff774b85e421de0b8d1338adf7f2e2454c734303</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/22478fba589bf9dfa1ff6225fb25ee8fcbb03693">22478fba589bf9dfa1ff6225fb25ee8fcbb03693</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/210725/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/313500/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/343618/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448859/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448856/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/343616/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448857/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448855/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456640/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 21 out of 21 jobs PASSED</strong></summary><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest(master)/7601/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/343617/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/210727/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/210725/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/210729/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/313500/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/343618/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448860/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448858/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/313499/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456641/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448859/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/210728/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448856/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/210726/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/343616/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448857/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/428961/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/448855/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/210724/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456640/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7601/jenkins-report.html">here</a>.</h5></details></html>

2020-12-09 13:18 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest(master)/7601/">test-portal-acceptance-pullrequest(master)#7601</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7601/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/dantewang/liferay-portal/pull/1833">dantewang#1833</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/69666.aspx">master - slnn > dantewang - PR#1833 - 2020-12-09[02:04:25]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/9860/">publish-spira-report#9860</a><br />

2020-12-10 03:29 UTC, dantewang requested changes
@slnn Please see my comments and resend. Also, please try to describe clearly in the commit message about why DDL needs unique structure version IDs but other DDM related models don't.

2020-12-10 03:29 UTC, dantewang commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
>  				_ownerRoleModel.getRoleId(), _defaultUserId));
@slnn Here the `ownerId` is set to `_defaultUserId` but the model is created by the sample user. Why `ddlRecordSetModel.getUserId()` is not passed here, like in the two DDM methods below?

Also I see there's a common method, the protected `newResourcePermissionModels(String, String, long)`. This method creates resource permission for site member role instead of user role, this is the reason that you don't call the common method, right? My question is, why are some of them have permission for user role while some of them have permission for site member role? Could you confirm?

2020-12-10 03:29 UTC, dantewang commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +	protected DDMStructureLinkModel newDDMStructureLinkModel(
@slnn No need to add a new method here. Use set `_companyId` like in `newDDMStorageLinkModel` above. Currently SampleSQLBuilder does not have support for multiple companies.

2020-12-10 03:29 UTC, dantewang commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +		long versionId) {
@slnn Please rename `versionId` parameters you add to `structureVersionId`

2020-12-10 03:29 UTC, closed without merging

2020-12-10 06:31 UTC, slnn commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
>  				_ownerRoleModel.getRoleId(), _defaultUserId));
Hi @dantewang 

I double checked the database, the ownerId here should be the real owner userId ddlRecordSetModel.getUserId(), I will change it.

For the resource permission,  from my note,  it should be the site member instead of the user, here is a typo.

2020-12-10 06:38 UTC, dantewang commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
>  				_ownerRoleModel.getRoleId(), _defaultUserId));
@slnn For site member role vs user role, please check DDL now and make correction, and add checks for other models to your list and revisit them later.

2020-12-10 06:38 UTC, slnn commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +	protected DDMStructureLinkModel newDDMStructureLinkModel(
Hi @dantewang 

I added a new method here because I only want to set _companyId to DDL's DDMStructureLinkModel, I did not know why we did not set  _companyId to DL's DDMStructureLinkModel,  if it also works well for DL, I will remove the new method.

2020-12-10 06:41 UTC, slnn commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
>  				_ownerRoleModel.getRoleId(), _defaultUserId));
I have double checked for DDL from DB, we need to generate owner, site member, Guest.

I will also check for other models with another ticket if we really need to update.

2020-12-10 06:47 UTC, slnn commented
> @slnn Please see my comments and resend. Also, please try to describe clearly in the commit message about why DDL needs unique structure version IDs but other DDM related models don't.

Hi @dantewang 

Other models also need the structure version IDs, but they should use their own structure version IDs, for DL, the id is `_defaultDLDDMStructureVersionId`,  for Journal , the id is` _defaultJournalDDMStructureVersionId`,  my changes for DDL is to use its own structure IDs like the head of master did instead of DL's.

2020-12-10 07:00 UTC, slnn commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
>  				_ownerRoleModel.getRoleId(), _defaultUserId));
Hi  @dantewang 

>  and add checks for other models to your list and revisit them later.

The other models here mean other DDL or DDM related models?

I found that for DDL or DDM related models such as  DDMStructureModel, DDMTemplateModel, the resource permission list contains Owner, Guest, User instead of Owner, Guest, Site Member,

I will double check it.

2020-12-11 04:01 UTC, slnn commented
Resend in https://github.com/dantewang/liferay-portal/pull/1834