Lps 127055 3 9
dantewang/liferay-portal pull request #1930
Opened 2021-03-09 09:40 UTC by slnn

Hi @dantewang 

This pull depends on https://github.com/dantewang/liferay-portal/pull/1929

/cc @tinatian

Lily

2021-03-09 09:40 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2021-03-09 09:40 UTC, slnn commented
ci:test:relevant

2021-03-09 09:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/2645/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-portal-source-format/builds/2645/jenkins-report.html">here</a>.</b></p>

2021-03-09 09:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/8528/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8528/jenkins-report.html">here</a>.</b></p>

2021-03-09 09:45 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dc8652d18acfc6f4c7bd2610357ed85940f1e895">dc8652d18acfc6f4c7bd2610357ed85940f1e895</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/slnn/liferay-portal/tree/LPS-127055-3-9">LPS-127055-3-9</a><br/>Branch GIT ID: <a href="https://github.com/slnn/liferay-portal/commit/0e7b797cb219f689d3de580a9116b0f7b9d52822">0e7b797cb219f689d3de580a9116b0f7b9d52822</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/2645/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/2645/jenkins-report.html">here</a>.</h5></details></html>

2021-03-09 11:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 9 out of 9 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 21 out of 21 jobs passed in 1 hour 25 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dc8652d18acfc6f4c7bd2610357ed85940f1e895">dc8652d18acfc6f4c7bd2610357ed85940f1e895</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dc8652d18acfc6f4c7bd2610357ed85940f1e895">dc8652d18acfc6f4c7bd2610357ed85940f1e895</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1616">Acceptance Upstream DXP (master) #1616</a></p><details><summary><strong>ci:test:stable - 9 out of 9 jobs PASSED</strong></summary><details><summary><strong>9 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456564/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/324438/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/436766/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456570/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456567/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3700/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456568/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456566/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467743/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 21 out of 21 jobs PASSED</strong></summary><details><summary><strong>21 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest(master)/8528/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/324439/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/436764/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456564/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/461999/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/324438/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/436766/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456571/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456569/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/436763/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467744/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456570/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/436765/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456567/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/324437/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3700/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456568/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/324440/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456566/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456565/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/467743/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8528/jenkins-report.html">here</a>.</h5></details></html>

2021-03-09 11:35 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-9.liferay.com/job/test-portal-source-format/2645/">test-portal-source-format#2645</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/2645/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/dantewang/liferay-portal/pull/1930">dantewang#1930</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/99845.aspx">master - slnn &gt; dantewang - PR#1930 - 2021-03-09[01:40:52]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/21307/">publish-spira-report#21307</a><br />

2021-03-10 12:12 UTC, dantewang commented on modules/util/portal-tools-sample-sql-builder/src/main/resources/com/liferay/portal/tools/sample/sql/builder/dependencies/company.ftl
> +<#list dataFactory.getSequence(dataFactory.maxVirtualInstanceCount) as virtualInstanceCount>
@slnn It seems in this ftl, the default company code and the additional company code are same.

I would like it to be changed in this way:

```
<#list dataFactory.newCompanyModels() as companyModel>

    ${dataFactory.toInsertSQL(companyModel)}

    ${dataFactory.toInsertSQL(dataFactory.newAccountModel(companyModel.webId))}

    ${dataFactory.toInsertSQL(dataFactory.newVirtualHostModel(companyModel.webId))}

    ....

<#list>
```

With this way, you create the default and additional companies in Java code, and loop on all the models instead of looping on the count. And your public methods won't need arrays as parameters.

2021-03-10 12:25 UTC, dantewang requested changes

2021-03-10 12:25 UTC, dantewang commented on modules/util/portal-tools-sample-sql-builder/src/main/resources/com/liferay/portal/tools/sample/sql/builder/dependencies/company.ftl
> +<#list dataFactory.getSequence(dataFactory.maxVirtualInstanceCount) as virtualInstanceCount>
@slnn Could you try this way?

2021-03-10 12:25 UTC, dantewang commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +		_groupCounter = new SimpleCounter(1);
@slnn Could you explain it in detail? Why can't you get the ids from the `_counter`? And if you use a separate counter, is it possible that the `_groupCounter.get()` produces duplicate number with what `_counter.get()` produces, because the default counter only skips `BenchmarksPropsValues.MAX_GROUP_COUNT + 1` counts?

2021-03-10 12:25 UTC, dantewang commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +			_currentGroupId = journalArticleModel.getGroupId();
@slnn Change to the current group Id should be done by the contextual change of the current group -- which means when we create a new group we should update the group ID, right?

2021-03-11 02:28 UTC, dantewang commented
@slnn LPS-128706 is in master now. Please make changes on current master and resend.

2021-03-11 02:28 UTC, closed without merging

2021-03-11 02:31 UTC, slnn commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +		_groupCounter = new SimpleCounter(1);
Hi @dantewang 

Please see this method that used to generate groups in SampleSQLBuilder:

```
public List<GroupModel> newGroupModels() {
		List<GroupModel> groupModels = new ArrayList<>(
			BenchmarksPropsValues.MAX_GROUP_COUNT);

		for (int i = 1; i <= BenchmarksPropsValues.MAX_GROUP_COUNT; i++) {
			groupModels.add(
				newGroupModel(
					i, getClassNameId(Group.class), i, "Site " + i, true));
		}

		return groupModels;
	}
```

In the method, we use the local variable `i` of the loop as the groupId, so no problem with it when we only generate the default company, however, when we generate more than one companies as this pull did just do a loop on companymodels, here will be a problem, for example, if we generate 1 default company, 1 virtual instance, each company contains 1 group, so the result is the different company will have a group which will have the same groupId 1, as the local variable `i` of the loop will be reset when generating data for next company. Based on the data of clean portal, the groupIds for different companies should be different too, and portal has a unique index IX_920CD8B1 on WikiNode (groupId, name), for us the name of WikiNode in each instance is the same, and the unique index not only wiki has, so I create a _groupCounter to generate the groupId to make sure the groupId will not repeat when generating more than one companies.

```
public List<GroupModel> newGroupModels() {
		List<GroupModel> groupModels = new ArrayList<>(
			BenchmarksPropsValues.MAX_GROUP_COUNT);

		for (int i = 1; i <= BenchmarksPropsValues.MAX_GROUP_COUNT; i++) {
			long groupId = _groupCounter.get();

			groupModels.add(
				newGroupModel(
					groupId, getClassNameId(Group.class), groupId, "Site " + i,
					true));
		}

		return groupModels;
	}
```

2021-03-11 02:38 UTC, dantewang commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +		_groupCounter = new SimpleCounter(1);
@slnn Thanks! However I'm still concerned about my second question.
Your `_groupCounter` starts from 1, while `_counter` starts from `BenchmarksPropsValues.MAX_GROUP_COUNT + 1` to skip the range of group IDs.
If there are multiple companies, the total group count should be `MAX_GROUP_COUNT` * total company count, right? In this way some of the groups may have the same id as some non-group data.

2021-03-11 02:48 UTC, slnn commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +		_groupCounter = new SimpleCounter(1);
yes, some of the groups may have the same id, but I did not see it broke anything, so I will try to make _counter starts from BenchmarksPropsValues.totalgroupcount + 1 to skip the range of all group IDs

2021-03-11 05:55 UTC, slnn commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +			_currentGroupId = journalArticleModel.getGroupId();
Hi @dantewang 

This change is aim to update the _defaultJournalArticleId,  as you said the current group Id should be done by the contextual change of the current group so the _defaultJournalArticleId need be updated when the groupId be changed.

2021-03-11 06:49 UTC, dantewang commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +			_currentGroupId = journalArticleModel.getGroupId();
@slnn The current group id should be updated in an earlier place unrelated to journal article model.

2021-03-11 06:59 UTC, slnn commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +			_currentGroupId = journalArticleModel.getGroupId();
Hi @dantewang 

The `_currentGroupId` is just a flag here, when the `journalArticleModel.getGroupId()` return a different groupId, it means that we need to update the _defaultJournalArticleId, please check the code, we use `journalArticleResourceModel's groupId `as `journalArticleModel's`, however,  `journalArticleResourceModel's groupId` came from  the loop for `newGroupModels()` in the `groups.ftl`, so what's your concern or question here?

2021-03-11 07:17 UTC, dantewang commented on modules/util/portal-tools-sample-sql-builder/src/main/java/com/liferay/portal/tools/sample/sql/builder/DataFactory.java
> +			_currentGroupId = journalArticleModel.getGroupId();
@slnn In the context, when I see `_currentGroupId`, I treat it as the group id of the current contextual group. So it's very weird to modify it in a method called `newJournalArticleModel`, regardless of what the real logic is. It should either be set as soon as we switch the contextual group, or be made non-field.