LPS-154947 Add new functionality to SystemProperties for moving module framework properties next
dantewang/liferay-portal pull request #2235
Opened 2022-07-01 14:14 UTC by W2jx

Hi @dantewang, @yuhai, I have fixed problems.

 problem details: https://github.com/dantewang/liferay-portal/pull/2233

2022-07-01 14:14 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-07-01 14:14 UTC, W2jx commented
ci:test:acceptance

2022-07-01 14:15 UTC, W2jx commented
ci:test:relevant

2022-07-01 14:15 UTC, W2jx commented
ci:test:sf

2022-07-01 14:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>acceptance</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3137/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3137/jenkins-report.html">here</a>.</b></p>

2022-07-01 14:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3442/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3442/jenkins-report.html">here</a>.</b></p>

2022-07-01 14:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/2723/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2723/jenkins-report.html">here</a>.</b></p>

2022-07-01 14:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/31e4a20dc53eb12ac4fd6af76734d508bdd4d461">31e4a20dc53eb12ac4fd6af76734d508bdd4d461</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/W2jx/liferay-portal/tree/LPS-154947-6-30">LPS-154947-6-30</a><br/>Branch GIT ID: <a href="https://github.com/W2jx/liferay-portal/commit/3ab10c40581a96b1e1d86723aeab270ea3d00296">3ab10c40581a96b1e1d86723aeab270ea3d00296</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2723/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2723/jenkins-report.html">here</a>.</h5></details></html>

2022-07-01 14:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/2723/">test-portal-source-format#2723</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/2723/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/dantewang/liferay-portal/pull/2235">dantewang#2235</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1894479856">[master] ci:test:sf - W2jx &gt; dantewang - PR#2235 - 2022-07-01[07:15:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/10029/">publish-testray-report#10029</a><br/></div></div>

2022-07-01 17:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 25 out of 26 jobs passed</h3><h3>:x: ci:test:relevant - 909 out of 932 jobs passed in 2 hours 46 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3488">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1257401_3442</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/31e4a20dc53eb12ac4fd6af76734d508bdd4d461">31e4a20dc53eb12ac4fd6af76734d508bdd4d461</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1414f5ca04e3956aefef8467d891297695689291">1414f5ca04e3956aefef8467d891297695689291</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3487">Acceptance Upstream DXP (master) #3487</a></p><details><summary><strong>ci:test:stable - 25 out of 26 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li>rest-builder-jdk8<ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/33677/"><strike>rest-builder-jdk8/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>25 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/92088/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36207/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/33660/">functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/31930/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93865/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/68056/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38649/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/80113/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36216/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/34182/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40430/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50695/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40158/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89229/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89230/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96708/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93509/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/92091/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/86437/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89501/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36214/">modules-unit-jdk8_stable/0/0</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40438/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93535/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89495/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96714/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 909 out of 932 jobs PASSED</strong></summary><div><h4>23 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3442/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41009/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93526/"><strike>functional-tomcat90-mysql57-jdk8/0/7</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93515/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/76614/"><strike>functional-tomcat90-mysql57-jdk8/1/9</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89237/"><strike>functional-tomcat90-mysql57-jdk8/3/2</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/91202/"><strike>functional-tomcat90-mysql57-jdk8/3/3</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40437/"><strike>functional-tomcat90-mysql57-jdk8/5/14</strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38646/"><strike>functional-tomcat90-mysql57-jdk8/8/9</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96738/"><strike>functional-tomcat90-mysql57-jdk8/16/3</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/80165/"><strike>functional-tomcat90-mysql57-jdk8/16/5</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/92085/"><strike>functional-tomcat90-mysql57-jdk8/22/24 [...]

2022-07-01 17:16 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:acceptance - 1165 out of 1229 jobs passed in 3 hours</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3488">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_3137</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/31e4a20dc53eb12ac4fd6af76734d508bdd4d461">31e4a20dc53eb12ac4fd6af76734d508bdd4d461</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1414f5ca04e3956aefef8467d891297695689291">1414f5ca04e3956aefef8467d891297695689291</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3487">Acceptance Upstream DXP (master) #3487</a></p><details><summary><strong>ci:test:acceptance - 1165 out of 1229 jobs PASSED</strong></summary><div><h4>64 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3137/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>archived-module-smoke-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38467/"><strike>archived-module-smoke-jdk8/0/0</strike></a></li></ul></li><li>archived-modules-test-jdk8<ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/34217/"><strike>archived-modules-test-jdk8/0/0</strike></a></li></ul></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/38679/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>functional-smoke-wildfly230-mariadb104-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/40455/"><strike>functional-smoke-wildfly230-mariadb104-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-db2111-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96762/"><strike>functional-tomcat90-db2111-jdk8/0/3</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/80163/"><strike>functional-tomcat90-db2111-jdk8/0/13</strike></a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50714/"><strike>functional-tomcat90-mysql57-jdk8/0/16</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39828/"><strike>functional-tomcat90-mysql57-jdk8/4/14</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96824/"><strike>functional-tomcat90-mysql57-jdk8/5/15</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/36163/"><strike>functional-tomcat90-mysql57-jdk8/6/19</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39824/"><strike>functional-tomcat90-mysql57-jdk8/14/6</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50715/"><strike>functional-tomcat90-mysql57-jdk8/14/8</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93600/"><strike>functional-tomcat90-mysql57-jdk8/20/4</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93549/"><strike>functional-tomcat90-mysql57-jdk8/21/2</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41032/"><strike>functional-tomcat90-mysql57-jdk8/25/9</strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/42643/"><strike>functional-tomcat90-mysql57-jdk8/27/12</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39846/"><strike>functional-tomcat90-mysql57-jdk8/30/10</strike></a></li></ul></li><li>functional-tomcat90-oracle193-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/39866/"><strike>functional-tomcat90-oracle193-jdk8/2/0</strike></a></li></ul></li><li>functional-tomcat90-sqlserver2017-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/41428/"><strike>functional-tomcat90-sqlserver2017-jdk8/1/11</strike></a></li></ul></li><li>functional-upgrade-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/81246/"><strike>functional-upgrade-tomcat90-mysql57-jdk8/0/0</strike></a></li></ul></li><li>modules-integration-mysql57-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89369/"><strike>modules-integration-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89363/"><strike>modules-integration-mysql57-jdk8/0/6</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96851/"><strike>modules-integration-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/86556/"><strike>modules-integration-mysql57-jdk8/0/17</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93589/"><strike>modules-integration-mysql57-jdk8/1/1</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96788/"><strike>modules-integration-mysql57-jdk8/1/2</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89309/"><strike>modules-integration-mysql57-jdk8/1/3</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93931/"><strike>modules-integration-mysql57-jdk8/1/5</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89310/"><strike>modules-integration-mysql57-jdk8/1/7</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/68103/"><strike>modules-integration-mysql57-jdk8/1/8</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89528/"><strike>modules-integration-mysql57-jdk8/1/11</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/93889/"><strike>modules-integration-mysql57-jdk8/1/12</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/76645/"><strike>modules-integration-mysql57-jdk8/1/13</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/96752/"><strike>modules-integration-mysql57-jdk8/1/21</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/89535/"><strike>modules-integration-mysql57-jdk8/1/22</strike [...]

2022-07-01 17:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3442/">test-portal-acceptance-pullrequest(master)#3442</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3442/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/dantewang/liferay-portal/pull/2235">dantewang#2235</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1894617588">[master] ci:test:relevant - W2jx &gt; dantewang - PR#2235 - 2022-07-01[07:15:18]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/9037/">publish-testray-report#9037</a><br/></div></div>

2022-07-01 20:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/3137/">test-portal-acceptance-pullrequest(master)#3137</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3137/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>acceptance<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/dantewang/liferay-portal/pull/2235">dantewang#2235</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1894801975">[master] ci:test:acceptance - W2jx &gt; dantewang - PR#2235 - 2022-07-01[07:15:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/7541/">publish-testray-report#7541</a><br/></div></div>

2022-07-04 07:49 UTC, yuhai commented on portal-kernel/src/com/liferay/portal/kernel/util/SystemProperties.java
> +		}
@W2jx you may directly return null, instead of returning value.

2022-07-04 07:54 UTC, yuhai commented on portal-impl/src/com/liferay/portal/verify/VerifyProperties.java
> +				}
@W2jx, refer to the code format in this method, please place if block to the new method. For the method **verifyModularizedSystemProperty**, it doesn't exist any usages in our codes after the commit. I suggest we deprecate the method. @dantewang, what do you think?

2022-07-04 07:57 UTC, yuhai commented on portal-kernel/test/unit/com/liferay/portal/kernel/util/SystemPropertiesTest.java
> +
@W2jx since the setUpClass and tearDownClass are only for testLoad(), please inline it to testLoad(). In addition, we may name the file as system.properties, it can avoid place file when getResources() in the testLoad().

2022-07-04 08:01 UTC, yuhai commented on portal-kernel/test/unit/com/liferay/portal/kernel/util/SystemPropertiesTest.java
> +	}
@W2jx for testGet(), You firstly set all test data and then assert them. This is not convenient for review. Please try to keep the order. Set one test data, and then assert it. Set the second test data, and then assert it.

2022-07-04 08:03 UTC, yuhai commented on portal-kernel/test/unit/com/liferay/portal/kernel/util/SystemPropertiesTest.java
> +		Assert.assertTrue(propertyNames.contains("test.gpn.key"));
@W2jx, just like you did in other test. Add Assert.assertNull(SystemProperties.get("test.gpn.key")) in the beginning in the testGetPropertyNames()

2022-07-04 08:08 UTC, dantewang commented on portal-impl/src/com/liferay/portal/verify/VerifyProperties.java
> +				}
@yuhai @W2jx If this is the case, we can remove it directly. However, why are usages of this method deleted?

2022-07-04 08:08 UTC, dantewang commented on portal-kernel/test/unit/com/liferay/portal/kernel/util/SystemPropertiesTest.java
> +
@W2jx Remember to "try-finally"

2022-07-04 08:10 UTC, yuhai commented on portal-kernel/test/unit/com/liferay/portal/kernel/util/SystemPropertiesTest.java
> +			Assert.assertEquals("test.gp.value", property.getValue());
@W2jx, please also add assert about key.

2022-07-04 08:16 UTC, dantewang requested changes

2022-07-04 08:55 UTC, W2jx commented on portal-impl/src/com/liferay/portal/verify/VerifyProperties.java
> +				}
Because in order to protect data, we provide a new method to get keys of properties for logic that does not require value，so the method verifyModularizedSystemProperty is canceled

2022-07-04 09:01 UTC, W2jx commented on portal-kernel/src/com/liferay/portal/kernel/util/SystemProperties.java
> +		}
I'll fix it.

2022-07-04 09:02 UTC, W2jx commented on portal-kernel/test/unit/com/liferay/portal/kernel/util/SystemPropertiesTest.java
> +
I'll fix it.

2022-07-04 09:03 UTC, W2jx commented on portal-kernel/test/unit/com/liferay/portal/kernel/util/SystemPropertiesTest.java
> +		Assert.assertTrue(propertyNames.contains("test.gpn.key"));
I'll fix it.

2022-07-04 09:12 UTC, W2jx commented on portal-kernel/src/com/liferay/portal/kernel/util/SystemProperties.java
> +	private static void _load(InputStream inputStream, Properties properties)
I'll fix it.

2022-07-04 09:13 UTC, W2jx commented on portal-kernel/src/com/liferay/portal/kernel/util/SystemProperties.java
> +				sb.append(line + StringPool.NEW_LINE);
I'll fix it.

2022-07-05 07:10 UTC, W2jx commented
Hi @dantewang , @yuhai. I've fixed everything, and updated the code

2022-07-05 09:58 UTC, yuhai commented on portal-kernel/src/com/liferay/portal/kernel/util/SystemProperties.java
> +				new UnsyncBufferedReader(new InputStreamReader(inputStream))) {
@W2jx, please inline the var inputStream

2022-07-05 10:02 UTC, yuhai commented on portal-kernel/test/unit/com/liferay/portal/kernel/util/SystemPropertiesTest.java
> +			SystemProperties.load(getClass().getClassLoader());
@W2jx, most cases use A.class.getClassLoader(), please use SystemPropertiesTest.class.getClassLoader()

2022-07-05 10:11 UTC, yuhai commented on portal-kernel/test/unit/com/liferay/portal/kernel/util/SystemPropertiesTest.java
> +	}
@W2jx, for this case, I want to do the below change:
1. add the below cases:
case1: value: "${test.key}${test.key}" to test SystemProperties#_resolveReference while loop.
case 2: value: "${test.key${test.key}}"

2. extract the value to var. For example,
for the code **SystemProperties.set("test.key", "test.value");**, define the var.
String testKey="test.key",
String testValue="test.value"

Since the code exists reference invoke, when reviewing the code, it is hard to find where the key or value was defined as the below.

2022-07-05 10:17 UTC, yuhai commented on portal-kernel/test/unit/com/liferay/portal/kernel/util/SystemPropertiesTest.java
> +			SystemProperties.getProperties(prefix, false);
@W2jx, I think test removePrefix:false is enough. You may remove the assert. 
```
Map<String, String> propertiesWithoutPrefix =
			SystemProperties.getProperties(prefix, true);

		Assert.assertTrue(propertiesWithoutPrefix.isEmpty());
```
If removePrefix:false can't get properties, when removePrefix:true, it must also get same result with false.

2022-07-06 10:35 UTC, closed without merging