Lps x 8 9 1
dantewang/liferay-portal pull request #2244
Opened 2022-08-09 10:22 UTC by W2jx

Hi @dantewang , I and @JanisZhang finished the modification about "*PanelApp.java".

2022-08-09 10:22 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2022-08-09 10:23 UTC, W2jx commented
ci:test:sf

2022-08-09 10:23 UTC, W2jx commented
ci:test:relevant

2022-08-09 10:24 UTC, W2jx commented
ci:test:acceptance

2022-08-09 10:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-source-format/1392/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1392/jenkins-report.html">here</a>.</b></p>

2022-08-09 10:28 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/62cb9118cecfdbe626e79eaec7e3554fdb6cbfd2">62cb9118cecfdbe626e79eaec7e3554fdb6cbfd2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/W2jx/liferay-portal/tree/LPS-X-8-9-1">LPS-X-8-9-1</a><br/>Branch GIT ID: <a href="https://github.com/W2jx/liferay-portal/commit/df7ab3ed8f4eab4aa499574d6c5baaec202c4972">df7ab3ed8f4eab4aa499574d6c5baaec202c4972</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-source-format/1392/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1392/jenkins-report.html">here</a>.</h5></details></html>

2022-08-09 10:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-source-format/1392/">test-portal-source-format#1392</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-source-format/builds/1392/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/dantewang/liferay-portal/pull/2244">dantewang#2244</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1940516594">[master] ci:test:sf - W2jx &gt; dantewang - PR#2244 - 2022-08-09[03:24:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/5448/">publish-testray-report#5448</a><br/></div></div>

2022-08-09 10:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/4051/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4051/jenkins-report.html">here</a>.</b></p>

2022-08-09 10:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>acceptance</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/4052/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4052/jenkins-report.html">here</a>.</b></p>

2022-08-09 10:55 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 11 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/62cb9118cecfdbe626e79eaec7e3554fdb6cbfd2">62cb9118cecfdbe626e79eaec7e3554fdb6cbfd2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/88619d19282875d72fcc5aea02166c664061d25a">88619d19282875d72fcc5aea02166c664061d25a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1940097445">EE Development Acceptance (master) - 3654 - 2022-08-08[10:11:25]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/4051/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4051/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/4051/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] &gt; Task :apps:application-list:application-list-api:compileJava FAILED
     [exec] &gt; Task :apps:frontend-js:frontend-js-loader-modules-extender-api:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:portal-template:portal-template-react-renderer-api:compileJava
     [exec] &gt; Task :apps:account:account-api:compileJava
     [exec] 
     [exec] &gt; Task :core:portal-bootstrap:buildSystemPackagesExtraManifest
     [exec] Unused Export-Package instructions: [java_cup.runtime.*, javax.xml.crypto.*, org.apache.bcel.*, org.apache.xml.dtm.*, org.apache.xml.res.*, org.apache.xml.utils.*, org.apache.xpath.*] 
     [exec] Export org.apache.logging.log4j.spi,  has 1,  private references [org.apache.logging.log4j.internal]
     [exec] Export org.hibernate.boot.archive.scan.spi,  has 1,  private references [org.hibernate.boot.archive.scan.internal]
     [exec] Export org.hibernate.boot.model.source.spi,  has 1,  private references [org.hibernate.boot.model.source.internal.hbm]
     [exec] Export org.hibernate.boot.registry,  has 2,  private references [org.hibernate.boot.cfgxml.internal, org.hibernate.boot.registry.classloading.internal]
     [exec] Export org.hibernate.boot.spi,  has 4,  private references [org.hibernate.boot.internal, org.hibernate.boot.jaxb.internal, org.hibernate.boot.model.source.internal.hbm, org.hibernate.internal]
     [exec] Export org.hibernate.cfg,  has 1,  private references [org.hibernate.internal.util.xml]
     [exec] Export org.hibernate.cfg.annotations,  has 1,  private references [org.hibernate.internal]
     [exec] Export org.hibernate.criterion,  has 1,  private references [org.hibernate.internal]
     [exec] Export org.hibernate.engine.jdbc.spi,  has 1,  private references [org.hibernate.engine.jdbc.internal]
     [exec] Export org.hibernate.engine.query.spi,  has 3,  private references [org.hibernate.hql.internal.ast, org.hibernate.hql.internal.ast.tree, org.hibernate.query.internal]
     [exec] Export org.hibernate.engine.spi,  has 5,  private references [org.hibernate.action.internal, org.hibernate.bytecode.enhance.internal.tracker, org.hibernate.engine.loading.internal, org.hibernate.internal, org.hibernate.resource.transaction.backend.jta.internal.synchronization]
     [exec] Export org.hibernate.event.spi,  has 1,  private references [org.hibernate.jpa.event.internal]
     [exec] Export org.hibernate.hql.spi.id,  has 1,  private references [org.hibernate.hql.internal.ast]</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-08-09 10:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:acceptance - 0 out of 1 jobs passed in 13 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/62cb9118cecfdbe626e79eaec7e3554fdb6cbfd2">62cb9118cecfdbe626e79eaec7e3554fdb6cbfd2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/88619d19282875d72fcc5aea02166c664061d25a">88619d19282875d72fcc5aea02166c664061d25a</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1940097445">EE Development Acceptance (master) - 3654 - 2022-08-08[10:11:25]</a></p><details><summary><strong>ci:test:acceptance - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/4052/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4052/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/4052/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>     [exec] &gt; Task :apps:application-list:application-list-api:compileJava FAILED
     [exec] 
     [exec] &gt; Task :apps:account:account-api:compileJava
     [exec] &gt; Task :apps:frontend-js:frontend-js-loader-modules-extender-api:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:frontend-taglib:frontend-taglib-react:jar
     [exec] &gt; Task :apps:frontend-taglib:frontend-taglib-react:autoUpdateXml SKIPPED
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':apps:application-list:application-list-api:compileJava'.
     [exec] &gt; Compilation failed; see the compiler error output for details.
     [exec] 
     [exec] * Try:
     [exec] Run with --info or --debug option to get more log output. Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':apps:application-list:application-list-api:compileJava'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:208)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:263)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:206)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:187)
     [exec]   at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:114)
     [exec]   at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
     [exec]   at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:62)
     [exec]   at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
     [exec]   at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
     [exec]   at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
     [exec]   at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter\$1.executeTask(EventFiringTaskExecuter.java:77)</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2022-08-09 11:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/4051/">test-portal-acceptance-pullrequest(master)#4051</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4051/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/dantewang/liferay-portal/pull/2244">dantewang#2244</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1940522619">[master] ci:test:relevant - W2jx &gt; dantewang - PR#2244 - 2022-08-09[03:43:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/9557/">publish-testray-report#9557</a><br/></div></div>

2022-08-09 12:38 UTC, dantewang requested changes
@W2jx Other parts looks good, just one thing, please see my comment.

2022-08-09 12:38 UTC, dantewang commented on modules/apps/account/account-admin-web/src/main/java/com/liferay/account/admin/web/internal/application/list/AccountEntriesAdminPanelApp.java
> +	private Portlet _portlet;
@W2jx Field reference does not need this `unbind = "-"`.

2022-08-09 13:15 UTC, W2jx commented on modules/apps/account/account-admin-web/src/main/java/com/liferay/account/admin/web/internal/application/list/AccountEntriesAdminPanelApp.java
> +	private Portlet _portlet;
I will fix it.

2022-08-11 05:07 UTC, W2jx commented
Hi @dantewang , there is an error when I execute ant all， For example PortletPanelAppAdapter has no portlet variable, it extends BasePanelApp and uses the method getPortlet in BasePanelApp，but we remove the method getPortlet in BasePanelApp

2022-08-11 06:46 UTC, dantewang commented
@W2jx OK I see. The setPortlet method is not only used by sub-classes. They are also used by some trackers.

I think this is somehow a backwards compatible thing for the adapter usages. If you register a PanelApp using OSGi component, you should not need the PanelAppRegistry to inject the portlet for you.

Please push `setPortlet` method to the adapter, and only `setPortlet` if the `PanelApp` instance is an adapter instance.

2022-08-15 01:25 UTC, closed without merging